name: ShapRapha
channels:
  - conda-forge
dependencies:
  - about-time=4.2.1
  - alembic=1.11.1
  - algopy=0.5.7
  - alive-progress=3.1.2
  - anyio=4.3.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - autograd=1.5
  - aws-c-auth=0.7.16
  - aws-c-cal=0.6.10
  - aws-c-common=0.9.13
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.5
  - aws-c-mqtt=0.10.2
  - aws-c-s3=0.5.2
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.2
  - aws-sdk-cpp=1.11.267
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - bokeh=3.3.4
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.3
  - cloudpickle=2.2.1
  - cma=3.2.2
  - cmaes=0.9.1
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - colorlog=6.7.0
  - comm=0.2.2
  - contourpy=1.0.7
  - cycler=0.11.0
  - cytoolz=0.12.3
  - dask=2023.5.0
  - dask-core=2023.5.0
  - dask-jobqueue=0.8.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - dill=0.3.6
  - distributed=2023.5.0
  - emcee=3.1.4
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fast-histogram=0.11
  - filelock=3.12.3
  - flatbuffers=23.3.3
  - fonttools=4.39.4
  - fqdn=1.5.1
  - freetype=2.12.1
  - fsspec=2023.5.0
  - future=0.18.3
  - gflags=2.2.2
  - glog=0.7.0
  - gmp=6.3.0
  - gmpy2=2.1.2
  - grapheme=0.6.0
  - greenlet=2.0.2
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - humanfriendly=10.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.6
  - importlib-metadata=6.6.0
  - importlib-resources=5.12.0
  - importlib_metadata=6.6.0
  - importlib_resources=5.12.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - ipywidgets=8.1.2
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - json5=0.9.24
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.4
  - jupyter_client=8.6.1
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.13.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.1.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.4
  - jupyterlab_widgets=3.0.10
  - kiwisolver=1.4.4
  - krb5=1.21.2
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230802.1
  - libarrow=15.0.0
  - libarrow-acero=15.0.0
  - libarrow-dataset=15.0.0
  - libarrow-flight=15.0.0
  - libarrow-flight-sql=15.0.0
  - libarrow-gandiva=15.0.0
  - libarrow-substrait=15.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.6.0
  - libcxx=16.0.6
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgoogle-cloud=2.17.0
  - libgoogle-cloud-storage=2.17.0
  - libgrpc=1.60.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm16=16.0.6
  - libnghttp2=1.58.0
  - libopenblas=0.3.25
  - libparquet=15.0.0
  - libpng=1.6.43
  - libprotobuf=4.25.1
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.5.1
  - libtorch=2.1.2
  - libutf8proc=2.8.0
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.6
  - libzlib=1.2.13
  - llvm-openmp=18.1.2
  - llvmlite=0.41.1
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - mako=1.2.4
  - markupsafe=2.1.2
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=3.0.2
  - mlxtend=0.22.0
  - more-itertools=9.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpl-scatter-density=0.7
  - mpmath=1.3.0
  - msgpack-python=1.0.7
  - multiprocess=0.70.14
  - munkres=1.1.4
  - nbclient=0.10.0
  - nbconvert=7.16.3
  - nbconvert-core=7.16.3
  - nbconvert-pandoc=7.16.3
  - nbformat=5.10.3
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - networkx=3.1
  - nomkl=1.0
  - notebook=7.1.2
  - notebook-shim=0.2.4
  - numba=0.58.1
  - numdifftools=0.9.41
  - numpy=1.24.4
  - onnxruntime=1.14.1
  - openjpeg=2.5.0
  - openssl=3.2.1
  - optuna=3.2.0
  - orc=1.9.2
  - overrides=7.7.0
  - packaging=23.1
  - pandas=1.5.3
  - pandoc=3.1.12.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.4.0
  - pathos=0.3.2
  - patsy=0.5.6
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=9.5.0
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - pooch=1.8.1
  - pox=0.3.4
  - ppft=1.7.6.8
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - protobuf=4.25.1
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=15.0.0
  - pycparser=2.22
  - pydoe=0.3.8
  - pygments=2.17.2
  - pymoo=0.6.0.1
  - pynisher=1.0.5
  - pyobjc-core=10.2
  - pyobjc-framework-cocoa=10.2
  - pyparsing=3.0.9
  - pyrfr=0.9.0
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-flatbuffers=24.3.25
  - python-json-logger=2.0.7
  - python_abi=3.11
  - pytorch=2.1.2
  - pytz=2023.3
  - pywin32=306
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0
  - pyzmq=25.1.2
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.34.0
  - regex=2023.5.5
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.18.0
  - salib=1.4.7
  - scipy=1.10.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.2
  - setuptools=69.2.0
  - shap=0.43.0
  - six=1.16.0
  - sleef=3.5.1
  - slicer=0.0.7
  - snappy=1.1.10
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sqlalchemy=2.0.15
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - swig=4.1.1
  - sympy=1.11.1
  - tblib=1.7.0
  - terminado=0.18.1
  - threadpoolctl=3.1.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.14.2
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - typing_utils=0.1.0
  - tzdata=2024a
  - uri-template=1.3.0
  - urllib3=2.0.2
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - wrapt=1.15.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.10.1
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.15.0
  - zstd=1.5.5
  - pip:
      - configspace==0.7.1
      - pflacco==1.2.2
      - scikit-learn==1.4.0
      - yahpo-gym==1.0.1
